sudo: false
language: node_js
node_js:
  - 6
  - 5
  - 4
matrix:
  fast_finish: true
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
    - /^greenkeeper.*$/
  except:
    - gh-pages
before_script:
  - npm prune
script:
  - npm run clean
  - npm run eslint
  - npm run cover
after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && .travis/after-all.sh || false'
