sudo: false
language: node_js
node_js:
  - 8
  - 7
  - 6
os:
  - linux
  - osx
cache: yarn
notifications:
  email: false
env:
  global:
    - CC_VERSION=0.5.1
branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - gh-pages
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-${CC_VERSION}-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - yarn install
before_script:
  - ./cc-test-reporter before-build
script:
  - yarn run clean
  - yarn run eslint
  - yarn run cover
  - yarn run build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
jobs:
  fast_finish: true
  include:
    - stage: release
      node_js: 8
      deploy:
        skip_cleanup: true
        provider: script
        script: npx travis-deploy-once "npx semantic-release"
      on:
        branch: master
